### ISSUE TITLE
Help! Project lead obsessed with regurgitation!

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#13]
Needs excess amounts of meditation and introspection

**Comment by SamHatoum** [comment]
lol

**Comment by SamHatoum** [comment]
I'll close this when I get back!

**Comment by SamHatoum** [comment]
bugs fixed, duplicates removed, enhancements not needed, help always welcome, invalid is always a possibility and questions are more than ever. Wont fix can't fix!

**Comment by alanning** [comment]
Yay!  Sam's back!!  :-)
