### ISSUE TITLE
Jasmine-unit tests run multiple times when there is more than one *-jasmine-unit.js file.

### ISSUE THREAD

**Issue by andyp22** [xolvio/jasmine-unit#22]
If there are multiple files in a Meteor app's "tests" directory labelled similar to *-jasmine-unit.js the jasmine-unit framework runs the whole suite of tests once for each file present. For example, if I have one file called "examples-jasmine-unit.js" and one file called "app-jasmine-unit.js" then all tests in both files are run twice with results being printed to the console for each batch of tests. Currently creating an example app, will post shortly.

**Comment by SamHatoum** [comment]
Aha, the riddle is solved! I was wondering why that happened. Thanks for reporting

**Comment by andyp22** [comment]
Glad to help!

Here is an example app if needed: https://github.com/andyp22/jasmine-unit-example-issue-22

**Comment by alanning** [comment]
Thanks @andyp22, the repro made it a lot easier to test the fix
