### ISSUE TITLE
Testing Methods in Packages?

### ISSUE THREAD

**Issue by StephenWalther** [xolvio/jasmine-unit#34]
Just started using jasmine-unit and trying to get my head around it.

Can I use jasmine-unit to unit test functions in packages?  Right now, I defined a function in my main Meteor app and a function in a package (which is used by the main Meteor app) but jasmine-unit is not finding the function defined in the package. Is that expected?

**Comment by alanning** [comment]
Velocity is mainly for testing apps, you can use Meteor's tinytest to test packages. There's also a project called munit that may be velocity compatible but I'm not sure what state it's in. 

Jasmine-unit will attempt to stub exported objects and functions from packages for you. You can see more by running:

`DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 meteor`

**Comment by StephenWalther** [comment]
Thanks alanning - makes sense!  I'm trying mocha-web-velocity instead for both unit/integration tests (although the repeated mocha test results on browser reload in the HTML reporter are driving me crazy  :) ).

**Comment by ghost** [comment]
You can also use the jasmine package (without -unit). You can use it in the same way as mocha-web-velocity. Should work fine. If not, let me know.

**Comment by alanning** [comment]
@StephenWalther FYI, we're planning on combining the `jasmine-unit` and `jasmine` packages together so you can do both integration and unit testing with just one package.  I think @Sanjo has already got most of the guts working.  Once we get something useable, we'll do something similar with mocha syntax.  Just for background, currently the `jasmine` and `mocha-web-velocity` packages are for integration testing (they run your tests in-context) and there's no `mocha` unit-testing story that I'm aware of.

Also, as a former ASP.NET & MVC'er, it's an honor to have you checking this out!  :-)

**Comment by davidworkman9** [comment]
It would be nice to be able to test packages as well, I currently have a large app that's actually got zero code that's not in a package. Tinytest is undocumented, and doesn't have the speed of unit tests.

**Comment by queso** [comment]
I can help with the documentation part of TinyTest if needed :)  I plan to release a PDF 'cheatsheet' of test helpers it has.

I believe https://www.npmjs.org/package/spacejam was an attempt to get munit working for package testing...
