### ISSUE TITLE
Router is not defined

### ISSUE THREAD

**Issue by poojabansal** [xolvio/jasmine-unit#40]
I added velocity quick start package to my application which is using iron-router. The sample tests run smoothly. However, getting an error of “Router is not defined”.
Here is the trace with DEBUG=1:

I20140813-11:08:59.412(-7)? stubbing template: button
I20140813-11:08:59.412(-7)? stubbing template: input
I20140813-11:08:59.413(-7)? stubbing template: form
I20140813-11:08:59.415(-7)? loading stub file: a1-package-stubs.js
I20140813-11:08:59.549(-7)? loading source file: /Users/pooja/myApp/lib/permissions.js
I20140813-11:08:59.550(-7)? loading source file: /Users/pooja/myApp/lib/router.js
I20140813-11:08:59.557(-7)? Error loading app files Router is not defined ReferenceError: Router is not defined
I20140813-11:08:59.557(-7)?   at Object.<anonymous> (/Users/pooja/myApp/lib/router.js:1:63)
I20140813-11:08:59.558(-7)?   at Module._compile (module.js:456:26)
I20140813-11:08:59.558(-7)?   at Object.Module._extensions..js (module.js:474:10)
I20140813-11:08:59.559(-7)?   at Module.load (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140813-11:08:59.559(-7)?   at Function.Module._load (module.js:312:12)
I20140813-11:08:59.559(-7)?   at Module.require (module.js:364:17)
I20140813-11:08:59.560(-7)?   at require (module.js:380:17)
I20140813-11:08:59.560(-7)?   at loadFile (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:105:7)
I20140813-11:08:59.560(-7)?   at Function.forEach (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140813-11:08:59.561(-7)?   at Object.loadFiles (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:34:5)
I20140813-11:08:59.561(-7)?   at Object.<anonymous> (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/loader-helper.js:43:14)
I20140813-11:08:59.561(-7)?   at Module._compile (module.js:456:26)
I20140813-11:08:59.562(-7)?   at Object.Module._extensions..js (module.js:474:10)
I20140813-11:08:59.562(-7)?   at Module.load (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140813-11:08:59.562(-7)?   at Function.Module._load (module.js:312:12)
I20140813-11:08:59.562(-7)?   at Module.require (module.js:364:17)
I20140813-11:08:59.563(-7)?   at require (module.js:380:17)
I20140813-11:08:59.563(-7)?   at Object.jasmine.loadHelpersInFolder (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140813-11:08:59.563(-7)?   at /Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140813-11:08:59.564(-7)?   at Array.forEach (native)
I20140813-11:08:59.564(-7)?   at Object.<anonymous> (/Users/pooja/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140813-11:08:59.566(-7)?   at Module._compile (module.js:456:26)
I20140813-11:08:59.566(-7)?   at Object.Module._extensions..js (module.js:474:10)
I20140813-11:08:59.566(-7)?   at Module.load (module.js:356:32)
I20140813-11:08:59.566(-7)?   at Function.Module._load (module.js:312:12)
I20140813-11:08:59.566(-7)?   at Function.Module.runMain (module.js:497:10)
I20140813-11:08:59.567(-7)?   at startup (node.js:119:16)
I20140813-11:08:59.567(-7)?   at node.js:906:3
I20140813-11:08:59.567(-7)? 
I20140813-11:08:59.573(-7)? creating junit xml report save path: /Users/pooja/myApp/tests/.reports/jasmine-unit
I20140813-11:08:59.575(-7)? patched JUnitXmlReporter.writeFile
I20140813-11:08:59.591(-7)? 
I20140813-11:08:59.592(-7)? GeometryComputationClass - 8 ms
I20140813-11:08:59.595(-7)?     calculates surface area of a sphere correctly - 4 ms
I20140813-11:08:59.595(-7)?     calculates surface area of a cube correctly - 0 ms
I20140813-11:08:59.598(-7)?     calculates volume a sphere correctly - 0 ms
I20140813-11:08:59.600(-7)?     calculates volume of a cube correctly - 1 ms
I20140813-11:08:59.600(-7)? 
I20140813-11:08:59.601(-7)? Finished in 0.019 seconds
I20140813-11:08:59.602(-7)? 4 tests, 4 assertions, 0 failures, 0 skipped

I also tried mrt update.

**Comment by alanning** [comment]
Hi, it looks like the iron-router community stub was not loaded. 

Can you post your .meteor/packages file contents pls?

Also, please run with "DEBUG=1 JASMINE_DEBUG=1 VELOCITY_DEBUG=1 meteor" and post the result to a public gist for us to review.

**Comment by poojabansal** [comment]
The contents of .meteor/package are:
standard-app-packages
bootstrap-3
accounts-password
iron-router
spin
http
accounts-ui-bootstrap-3
event-hooks
collection2
autoform
winston
winston-client
velocity-quick-start

jasmine-unit
mocha-web-velocity
jasmine
velocity-html-reporter

And, here is the gist url: https://gist.github.com/poojabansal/307fcded99d004be2dfa
with the debug logs.

**Comment by alanning** [comment]
Strange... is there a link to `iron-router` in your app's packages directory?

**Comment by poojabansal** [comment]
Iron-router is referenced by these two packages in the packages directory: package-stubber and accounts-ui-bootstrap-3.

**Comment by alanning** [comment]
Hmm, `package-stubber` doesn't see dependent packages.  If you add iron-router via `mrt add iron-router`, does that fix it?

**Comment by poojabansal** [comment]
Running 'mrt add iron-router' doesn't solve the problem.
Also tried, 'mrt remove iron-router' before 'mrt add iron-router' and that also didn't work.

**Comment by poojabansal** [comment]
Figured it out: Meteor had to be updated upon which the Router issue went away, but got another issue with SimpleSchema.RegEx.Id as discussed in https://github.com/xolvio/jasmine-unit/issues/33.
Thanks Adrian for helping.
