### ISSUE TITLE
Tests re-run even when no file has changed

### ISSUE THREAD

**Issue by yourcelf** [xolvio/jasmine-unit#44]
Initial discussion here: https://groups.google.com/forum/#!topic/velocity-core/la7zKgFu8gI

Tests are rerunning on loop even when no project file is changed.  My repository is https://github.com/AdmitHub/Admit/tree/commerce.  I start running meteor with:

```
meteor --settings settings.json
```

and unit tests begin running on repeat.  After adding some console debugging to https://github.com/xolvio/jasmine-unit/blob/885dde77a96390d0fd31b03756f837f482db2ef1/main.js#L201, I found that the following sequence is happening:
1. A "removed" is triggered for the unit test file (I only have one so far).
2. An "added" is triggered for the same unit test file.
3. The package stubber loads.
4. The unit tests run twice.
5. npm starts updating dependencies, and the sequence repeats back to 1.

During that cycle, I watched the one unit test file from (1) and (2) with inotifywatch, and it reported two accesses and two close_nowrites, but no removals or additions.

Here is a DEBUG dump of the test run: https://gist.github.com/yourcelf/884a08245d52331ebbfc

**Comment by alanning** [comment]
Removing the `npm` package fixes it on my machine (OSX).  The npm package isn't actually being used anywhere in the app so its not needed.  Not sure what was causing it to freak out.

Here's the console output once I removed the `npm` package:  https://gist.github.com/alanning/8722e785c645bb6e51bb

**Comment by alanning** [comment]
Another user also noticed this happening:  https://github.com/meteorhacks/npm/issues/34

Not sure if he's using jasmine-unit or not.

**Comment by yourcelf** [comment]
I traced this back to an interaction between npm, velocity, and the `path` npm package.  I've opened a new issue for this as a debug/error reporting problem with velocity: meteor-velocity/velocity#101.  Closing here as this isn't really a problem with `jasmine-unit` at all.

**Comment by alanning** [comment]
Awesome job tracking this down!
