### ISSUE TITLE
package initial load time too long

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#5]
Since adding karma and karma-coffee-preprocessor, adding the `velocity-jasmine-unit` test to a meteor app takes a long time.  It's a one-time thing but that's a bad first impression.

I think this is due to the size of karma / karma-coffee-preprocessor.

If that's true then we can do some work to improve the load time.
1. only load karma/karma-coffee-preprocessor if coffeescript is used
2. if it is used, explore some other way to preprocess the coffeescript

I'm pretty sure I can do 1 based on something similar I've done with 'weak' package dependencies.  

For 2, if there aren't any hard requirements for karma, I'd imagine there are smaller packages that will compile the coffeescript.

**Comment by xolvio** [comment]
good point
we could just copy the code of the preprocessor and include only that. Karma is not needed

**Comment by xolvio** [comment]
Fixed https://github.com/xolvio/velocity-jasmine-unit/commit/d04c52b213ac15a0b66ed364a13cff8395c003bd
