### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#9]
What do you think about changing the package name to just, "jasmine-unit"?

**Comment by xolvio** [comment]
sure, why not

**Comment by alanning** [comment]
Updated code in `rename` branch: https://github.com/xolvio/velocity-jasmine-unit/tree/rename

To do the rename properly, we need to do these three things in conjunction:
- rename github repository
- merge in `rename` branch
- publish updated package to atmosphere (with new version number)

That should keep the `velocity` example app working.

**Comment by xolvio** [comment]
done
